use_gpu: True
device: 0
seed: 12345
federate:
  method: FjORD
  mode: standalone
  total_round_num: 1000
  client_num: 1100
  sample_client_num: 110
  resource_info_file: data/client_device_capacity
  augmentation_factor: 0.03
  merge_test_data: True
  make_global_eval: True
data:
  root: data/
  type: shakespeare
  splits: [0.8,0.0,0.2]
  subsample: 0.2
dataloader:
  batch_size: 64
model:
  type: lstm_od
  in_channels: 80
  out_channels: 80
  embed_size: 8
  hidden: 256
  dropout: 0.0
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 0.8
    weight_decay: 0.0
criterion:
  type: character_loss
trainer:
  type: fjordnlptrainer
eval:
  best_res_update_round_wise_key: test_acc
  freq: 10
  start_interval_eval_round: 10
  metrics: ['acc', 'correct']
fjord:
  use: True
  p_s: [0.2, 0.4, 0.6, 0.8, 1.0]
  client_tier_allocation: 'uniform'
  know_distill: False
